
services:
  api:
    image: mixtape-api:0.0.1-SNAPSHOT
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      DB_PATH: db
      ISSUER_HOST: auth-server
    depends_on:
      - db
      - auth-server
  db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: mixtape
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  auth-server:
    image: spotify-auth-server:0.0.1-SNAPSHOT
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    environment:
      DB_HOST: db
      HOSTNAME: localhost
    depends_on:
      - db