version: "3.9"

services:
  proxy:
    image: mixtape-proxy:0.0.1
    ports:
      - target: 80
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - backend
    depends_on:
      - auth-server
      - db
      - api
  db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: mixtape
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend
  api:
    image: mixtape-api:0.0.1-SNAPSHOT
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      DB_PATH: db
      ISSUER_HOST: auth-server
      ISSUER_PORT: 9001
    depends_on:
      - db
      - auth-server
    networks:
      - backend
  auth-server:
    image: spotify-auth-server:0.0.1-SNAPSHOT
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      - target: 9000
        published: 9001
        protocol: tcp
        mode: ingress
    environment:
      DB_HOST: db
      SERVER_PORT: 9000
      # SERVER_ADDR: 0.0.0.0
      # EXTERNAL_PORT: 9000
    depends_on:
      - db
    networks:
      - backend
networks:
  host:
    external: true
  frontend:
    driver: bridge
  backend:
    driver: overlay
    attachable: true