
spring:
  datasource:
    url: jdbc:postgresql://${DB_PATH:localhost}:5432/mixtape
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${ISSUER_HOST:auth.mixtape.local}:9000

logging:
  level:
    root: info

# DB_PATH: localhost
# ISSUER_HOST: auth.mixtape.local