
spring:
  profiles:
    active: ${MIXTAPE_PROFILE:default}
  datasource:
    url: jdbc:postgresql://${DB_PATH:localhost}:5432/mixtape
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${ISSUER_HOST:auth.mixtape.local}:${ISSUER_PORT:9000}

logging:
  level:
    root: info

client:
  client-id: df9bd9e5ec41469baf91e29921d605a9
  client-secret: 1f740b22a8984436bb87e41d7fa23295

# DB_PATH: localhost
# ISSUER_HOST: auth.mixtape.local