
spring:
  profiles:
    active: ${MIXTAPE_PROFILE:default}
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    url: jdbc:postgresql://${DB_PATH:localhost}:5432/mixtape
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${ISSUER_HOST:auth.mixtape.local}:${ISSUER_PORT:9000}
logging:
  level:
    root: info

client:
  client-id: df9bd9e5ec41469baf91e29921d605a9
  client-secret: 1f740b22a8984436bb87e41d7fa23295
notification:
  app-id: ce9a6e81-4492-4d92-aa9f-cf2861d01632
  app-key: OWVlYTFmMTYtN2QyYy00Mzk1LTgxMDItM2E2NDY5MzE2Y2Zi

aws:
  playlist-pic-bucket-url: https://playlist-pics.s3.amazonaws.com
  db-secrets-id: rds!db-6f51bd14-4f86-40c7-8e33-2a21b081cff2
# DB_PATH: localhost
# ISSUER_HOST: auth.mixtape.local