spring:
  datasource:
    url: jdbc:postgresql://mixtape.cosucasfyf1s.us-east-2.rds.amazonaws.com:5432/mixtape
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          spotify-idp:
            provider: spotify
            client-id: df9bd9e5ec41469baf91e29921d605a9
            client-secret: 1f740b22a8984436bb87e41d7fa23295
            scope:
              - user-read-private
              - user-read-email
              - user-read-playback-state
              - user-modify-playback-state
              - user-follow-read
              - user-read-recently-played
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: https://auth.getmixtapeapplication.com/login/oauth2/code/spotify-idp

mixtape:
  security:
    issuer-uri: https://auth.getmixtapeapplication.com

logging:
  level:
    root: info
